# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# WORK IN PROGRESS


class Ui_ProfileInterface(object):
    def setupUi(self, ProfileInterface):
        ProfileInterface.setObjectName("ProfileInterface")
        ProfileInterface.resize(656, 433)
        self.centralwidget = QtWidgets.QWidget(ProfileInterface)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupFiles = QtWidgets.QGroupBox(self.centralwidget)
        self.groupFiles.setAlignment(QtCore.Qt.AlignCenter)
        self.groupFiles.setObjectName("groupFiles")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupFiles)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_del_audio = QtWidgets.QPushButton(self.groupFiles)
        self.btn_del_audio.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_del_audio.setObjectName("btn_del_audio")
        self.gridLayout_3.addWidget(self.btn_del_audio, 3, 0, 1, 1)
        self.audio_list = QtWidgets.QListWidget(self.groupFiles)
        self.audio_list.setObjectName("audio_list")
        self.gridLayout_3.addWidget(self.audio_list, 0, 0, 2, 2)
        self.btn_add_audio = QtWidgets.QPushButton(self.groupFiles)
        self.btn_add_audio.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_add_audio.setObjectName("btn_add_audio")
        self.gridLayout_3.addWidget(self.btn_add_audio, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupFiles, 0, 0, 1, 1)
        self.groupProfiles = QtWidgets.QGroupBox(self.centralwidget)
        self.groupProfiles.setAlignment(QtCore.Qt.AlignCenter)
        self.groupProfiles.setObjectName("groupProfiles")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupProfiles)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_del_sequence = QtWidgets.QPushButton(self.groupProfiles)
        self.btn_del_sequence.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_del_sequence.setObjectName("btn_del_sequence")
        self.gridLayout_4.addWidget(self.btn_del_sequence, 1, 2, 1, 1)
        self.btn_new_sequence = QtWidgets.QPushButton(self.groupProfiles)
        self.btn_new_sequence.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_new_sequence.setObjectName("btn_new_sequence")
        self.gridLayout_4.addWidget(self.btn_new_sequence, 1, 1, 1, 1)
        self.combo = QtWidgets.QComboBox(self.groupProfiles)
        self.combo.setObjectName("combo")
        self.gridLayout_4.addWidget(self.combo, 0, 1, 1, 2)
        self.sequence_list = QtWidgets.QListWidget(self.groupProfiles)
        self.sequence_list.setMinimumSize(QtCore.QSize(0, 200))
        self.sequence_list.setObjectName("sequence_list")
        self.gridLayout_4.addWidget(self.sequence_list, 2, 1, 1, 2)
        self.btn_pop = QtWidgets.QPushButton(self.groupProfiles)
        self.btn_pop.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_pop.setObjectName("btn_pop")
        self.gridLayout_4.addWidget(self.btn_pop, 4, 2, 1, 1)
        self.btn_append = QtWidgets.QPushButton(self.groupProfiles)
        self.btn_append.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_append.setObjectName("btn_append")
        self.gridLayout_4.addWidget(self.btn_append, 4, 1, 1, 1)
        self.player_btn = QtWidgets.QPushButton(self.groupProfiles)
        self.player_btn.setObjectName("player_btn")
        self.gridLayout_4.addWidget(self.player_btn, 5, 1, 1, 2)
        self.gridLayout_2.addWidget(self.groupProfiles, 0, 2, 1, 1)
        ProfileInterface.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ProfileInterface)
        self.statusbar.setObjectName("statusbar")
        ProfileInterface.setStatusBar(self.statusbar)

        self.retranslateUi(ProfileInterface)
        QtCore.QMetaObject.connectSlotsByName(ProfileInterface)

    def retranslateUi(self, ProfileInterface):
        _translate = QtCore.QCoreApplication.translate
        ProfileInterface.setWindowTitle(_translate(
            "ProfileInterface", "Интерфейс профиля"))
        self.groupFiles.setTitle(_translate("ProfileInterface", "Аудиофайлы"))
        self.btn_del_audio.setText(_translate("ProfileInterface", "Удалить"))
        self.btn_add_audio.setText(_translate("ProfileInterface", "Добавить"))
        self.groupProfiles.setTitle(_translate(
            "ProfileInterface", "Последовательность"))
        self.btn_del_sequence.setText(
            _translate("ProfileInterface", "Удалить"))
        self.btn_new_sequence.setText(
            _translate("ProfileInterface", "Создать"))
        self.btn_pop.setText(_translate(
            "ProfileInterface", "Убрать последнее"))
        self.btn_append.setText(_translate(
            "ProfileInterface", "Добавить аудио"))
        self.player_btn.setText(_translate(
            "ProfileInterface", "Запустить плеер"))


class Ui_NewAudio(object):
    def setupUi(self, NewAudio):
        NewAudio.setObjectName("NewAudio")
        NewAudio.resize(300, 184)
        NewAudio.setMinimumSize(QtCore.QSize(300, 0))
        self.gridLayout = QtWidgets.QGridLayout(NewAudio)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(NewAudio)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.audio_title = QtWidgets.QLineEdit(NewAudio)
        self.audio_title.setObjectName("audio_title")
        self.gridLayout.addWidget(self.audio_title, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(NewAudio)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.audio_path = QtWidgets.QLineEdit(NewAudio)
        self.audio_path.setObjectName("audio_path")
        self.gridLayout.addWidget(self.audio_path, 3, 0, 1, 1)
        self.btn_select_path = QtWidgets.QPushButton(NewAudio)
        self.btn_select_path.setObjectName("btn_select_path")
        self.gridLayout.addWidget(self.btn_select_path, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancel = QtWidgets.QPushButton(NewAudio)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_save = QtWidgets.QPushButton(NewAudio)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 2)

        self.retranslateUi(NewAudio)
        QtCore.QMetaObject.connectSlotsByName(NewAudio)

    def retranslateUi(self, NewAudio):
        _translate = QtCore.QCoreApplication.translate
        NewAudio.setWindowTitle(_translate("NewAudio", "Новое аудио"))
        self.label.setText(_translate("NewAudio", "Название"))
        self.label_2.setText(_translate("NewAudio", "Путь к файлу"))
        self.btn_select_path.setText(_translate("NewAudio", "Выбрать"))
        self.btn_cancel.setText(_translate("NewAudio", "Отмена"))
        self.btn_save.setText(_translate("NewAudio", "Сохранить"))


class Ui_ProfileSelection(object):
    def setupUi(self, ProfileSelection):
        ProfileSelection.setObjectName("ProfileSelection")
        ProfileSelection.resize(271, 116)
        self.gridLayout = QtWidgets.QGridLayout(ProfileSelection)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_new = QtWidgets.QPushButton(ProfileSelection)
        self.btn_new.setObjectName("btn_new")
        self.gridLayout.addWidget(self.btn_new, 2, 1, 1, 1)
        self.combo = QtWidgets.QComboBox(ProfileSelection)
        self.combo.setObjectName("combo")
        self.gridLayout.addWidget(self.combo, 1, 0, 1, 3)
        self.btn_open = QtWidgets.QPushButton(ProfileSelection)
        self.btn_open.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_open.setObjectName("btn_open")
        self.gridLayout.addWidget(self.btn_open, 2, 2, 1, 1)
        self.btn_del = QtWidgets.QPushButton(ProfileSelection)
        self.btn_del.setObjectName("btn_del")
        self.gridLayout.addWidget(self.btn_del, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(ProfileSelection)
        self.label.setMaximumSize(QtCore.QSize(16777215, 19))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)

        self.retranslateUi(ProfileSelection)
        QtCore.QMetaObject.connectSlotsByName(ProfileSelection)

    def retranslateUi(self, ProfileSelection):
        _translate = QtCore.QCoreApplication.translate
        ProfileSelection.setWindowTitle(
            _translate("ProfileSelection", "Выбор профиля"))
        self.btn_new.setText(_translate("ProfileSelection", "Новый"))
        self.btn_open.setText(_translate("ProfileSelection", "Открыть"))
        self.btn_del.setText(_translate("ProfileSelection", "Удалить"))
        self.label.setText(_translate("ProfileSelection", "Выберите профиль"))


class Ui_NewProfile(object):
    def setupUi(self, NewProfile):
        NewProfile.setObjectName("NewProfile")
        NewProfile.resize(232, 123)
        self.gridLayout = QtWidgets.QGridLayout(NewProfile)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_back = QtWidgets.QPushButton(NewProfile)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 2, 0, 1, 1)
        self.btn_save = QtWidgets.QPushButton(NewProfile)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout.addWidget(self.btn_save, 2, 1, 1, 1)
        self.line = QtWidgets.QLineEdit(NewProfile)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(NewProfile)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(NewProfile)
        QtCore.QMetaObject.connectSlotsByName(NewProfile)

    def retranslateUi(self, NewProfile):
        _translate = QtCore.QCoreApplication.translate
        NewProfile.setWindowTitle(_translate("NewProfile", "Создание профиля"))
        self.btn_back.setText(_translate("NewProfile", "Отмена"))
        self.btn_save.setText(_translate("NewProfile", "Сохранить"))
        self.label.setText(_translate(
            "NewProfile", "Введите имя нового профиля"))


class Ui_NewSequence(object):
    def setupUi(self, NewSequence):
        NewSequence.setObjectName("NewSequence")
        NewSequence.resize(301, 123)
        self.gridLayout = QtWidgets.QGridLayout(NewSequence)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_back = QtWidgets.QPushButton(NewSequence)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout.addWidget(self.btn_back, 2, 0, 1, 1)
        self.btn_save = QtWidgets.QPushButton(NewSequence)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout.addWidget(self.btn_save, 2, 1, 1, 1)
        self.line = QtWidgets.QLineEdit(NewSequence)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(NewSequence)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(NewSequence)
        QtCore.QMetaObject.connectSlotsByName(NewSequence)

    def retranslateUi(self, NewSequence):
        _translate = QtCore.QCoreApplication.translate
        NewSequence.setWindowTitle(_translate(
            "NewSequence", "Создание последовательности"))
        self.btn_back.setText(_translate("NewSequence", "Отмена"))
        self.btn_save.setText(_translate("NewSequence", "Сохранить"))
        self.label.setText(_translate(
            "NewSequence", "Введите имя новой последовательности"))


class Ui_Player(object):
    def setupUi(self, player):
        player.setObjectName("Player")
        player.resize(258, 119)
        self.gridLayout = QtWidgets.QGridLayout(player)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(player)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(
            self.label, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.prev = QtWidgets.QLabel(player)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.prev.setFont(font)
        self.prev.setText("")
        self.prev.setObjectName("prev")
        self.gridLayout.addWidget(
            self.prev, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.now_playing = QtWidgets.QLabel(player)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.now_playing.setFont(font)
        self.now_playing.setText("")
        self.now_playing.setObjectName("now_playing")
        self.gridLayout.addWidget(
            self.now_playing, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.next = QtWidgets.QLabel(player)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.next.setFont(font)
        self.next.setText("")
        self.next.setObjectName("next")
        self.gridLayout.addWidget(
            self.next, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.prev_btn = QtWidgets.QPushButton(player)
        self.prev_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.prev_btn.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.prev_btn.setFont(font)
        self.prev_btn.setObjectName("prev_btn")
        self.gridLayout.addWidget(
            self.prev_btn, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.pause_btn = QtWidgets.QPushButton(player)
        self.pause_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.pause_btn.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pause_btn.setFont(font)
        self.pause_btn.setObjectName("pause_btn")
        self.gridLayout.addWidget(
            self.pause_btn, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.next_btn = QtWidgets.QPushButton(player)
        self.next_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.next_btn.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.next_btn.setFont(font)
        self.next_btn.setObjectName("next_btn")
        self.gridLayout.addWidget(
            self.next_btn, 2, 2, 1, 1, QtCore.Qt.AlignLeft)

        self.retranslateUi(player)
        QtCore.QMetaObject.connectSlotsByName(player)

    def retranslateUi(self, player):
        _translate = QtCore.QCoreApplication.translate
        player.setWindowTitle(_translate("player", "Плеер"))
        self.label.setText(_translate("player", "Сейчас играет:"))
        self.prev_btn.setText(_translate("player", "⏪"))
        self.pause_btn.setText(_translate("player", "⏵"))
        self.next_btn.setText(_translate("player", "⏩"))


class Ui_Hello(object):
    def setupUi(self, Hello):
        Hello.setObjectName("Hello")
        Hello.resize(312, 379)
        self.gridLayout = QtWidgets.QGridLayout(Hello)
        self.gridLayout.setObjectName("gridLayout")
        self.image = QtWidgets.QLabel(Hello)
        self.image.setMinimumSize(QtCore.QSize(300, 300))
        self.image.setMaximumSize(QtCore.QSize(300, 300))
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 1, 0, 1, 1)
        self.contacts = QtWidgets.QLabel(Hello)
        self.contacts.setObjectName("contacts")
        self.gridLayout.addWidget(self.contacts, 2, 0, 1, 1)
        self.btn_hello = QtWidgets.QPushButton(Hello)
        self.btn_hello.setObjectName("btn_hello")
        self.gridLayout.addWidget(self.btn_hello, 3, 0, 1, 1)

        self.retranslateUi(Hello)
        QtCore.QMetaObject.connectSlotsByName(Hello)

    def retranslateUi(self, Hello):
        _translate = QtCore.QCoreApplication.translate
        Hello.setWindowTitle(_translate("Hello", "Приветики девачбки"))
        self.contacts.setText(_translate("Hello", "telegram: @erytw"))
        self.btn_hello.setText(_translate("Hello", "Привет!"))
